### ISSUE TITLE
The use of faux-chinese 'sum ting wrong' on front page is inappropriate

### ISSUE THREAD

**Issue by nielm** [FOSDEM/volunteers#16]
Title says it all - it's certainly anti-inclusive and borderline racist. 

PR #15 fixes.

**Comment by emanuil-tolev** [comment]
I was under the impression the overall text had changed anyway. This may be an artifact of having multiple forks and sources of this code, and I suspect it was changed elsewhere, then the live deployment changed to point to this copy of the repo. I'm following up - we should probably be using this repo anyway since it's the obvious one.

**Comment by emanuil-tolev** [comment]
Merged, leaving issue open until deployed live

**Comment by RichiH** [comment]
I am positive we removed this when it was first pointed out. Thanks for flagging and fixing.

**Comment by pieterdp** [comment]
Has been merged and deployed live.

Pieter
